version: 1.0.{build}
image: Visual Studio 2022

environment:
  PATH: $(PATH);C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\msys64\opt\bin
  MINGW_PREFIX: C:\msys64\mingw64

install:
  - pacman -S --noconfirm --needed base-devel gtk-doc libtool automake autoconf pkgconf ccache mingw-w64-cross-gcc
  - where pkgconf
  - where autoreconf
  - where gcc
  - where ccache
  - for %%c in (c++ cc cpp gcc g++ i686-pc-msys-g++ i686-pc-msys-c++ i686-pc-msys-gcc i686-w64-mingw32-g++ i686-w64-mingw32-c++ i686-w64-mingw32-gcc x86_64-pc-msys-g++ x86_64-pc-msys-c++ x86_64-pc-msys-gcc x86_64-w64-mingw32-g++ x86_64-w64-mingw32-c++ x86_64-w64-mingw32-gcc) do mklink "C:\msys64\usr\lib\ccache\bin\%%c.exe" "C:\msys64\usr\bin\ccache.exe"

clone_script:
  - git config --global core.autocrlf false
  - git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%

build_script:
  - mklink /D msys64 C:\msys64
  # - media-autobuild_suite.bat
