version: 1.0.{build}
image: Visual Studio 2022

environment:
  PATH: $(PATH);C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\msys64\opt\bin
  MINGW_PREFIX: C:\msys64\mingw64

install:
  - pacman -S --noconfirm --needed base-devel autoconf pkgconf
  - where pkgconf
  - where autoreconf

clone_script:
  - git config --global core.autocrlf false
  - git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%

build_script:
  - mklink /D msys64 C:\msys64
  - media-autobuild_suite.bat
